name: Build and Release
on:
  push:
    tags:
      - 'v*'  # 模式匹配所有 v 开头的 tag
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run build script
        shell: cmd
        run: |
          mkdir ffmpeg
          mkdir downloads
          echo "Placeholder" > downloads/.gitkeep
          build.bat
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: |
            buildDist/M3U8_Downloader.exe
            buildDist/config.ini
            buildDist/ffmpeg/
            buildDist/downloads/
            
  release:
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-package
          path: ./artifacts
          
      - name: Create structured ZIP  # 新增的关键步骤
        run: |
          mkdir -p package/ffmpeg package/downloads
          cp artifacts/M3U8_Downloader.exe package/
          cp artifacts/config.ini package/
          cp artifacts/ffmpeg/* package/ffmpeg/
          cp artifacts/downloads/.gitkeep package/downloads/
          
          cd package
          zip -r ../M3U8_Downloader-${{ github.ref_name }}.zip *
          cd ..
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: M3U8_Downloader-${{ github.ref_name }}.zip  # 改为只上传ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
