name: Build and Release
on:
  push:
    tags:
      - 'v*'  # 模式匹配所有 v 开头的 tag
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # 使用你项目所需的Python版本
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run build script
        shell: cmd
        run: |
          # 创建必要的目录
          mkdir ffmpeg
          mkdir downloads
          # 执行打包脚本
          build.bat
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: |
            buildDist/M3U8_Downloader.exe
            buildDist/config.ini
            buildDist/ffmpeg/
            buildDist/downloads/
            
  release:
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/')  # 只有 tag 触发时才发布
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-package
          path: ./artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/M3U8_Downloader.exe
            artifacts/config.ini
            artifacts/ffmpeg/*
            artifacts/downloads/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
